# Mongo-Express has know vulnerbilities, it is suggested that you only use it for development.

version: "3"
services:
    
    mongodb:
        hostname: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=test_db
            - HOME=/data/db
        volumes:
            - mongodb-config:/data/configdb
            - mongodb-data:/data/db
        networks:
            - mongo-network
        ports:
            - 27017:27017
        restart: always
        image: mongo:latest
    
    mongo-express:
      hostname: mongo-express
      environment:
          - ME_CONFIG_BASICAUTH_USERNAME=admin
          - ME_CONFIG_BASICAUTH_PASSWORD=admin
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      networks:
        - mongo-network
      ports:
          - 8081:8081
      restart: always
      image: mongo-express:latest

networks:
    mongo-network:
        driver: bridge
<<<<<<< HEAD:compose.yaml

volumes:
    mongodb-config:
    mongodb-data:
=======
>>>>>>> a2782df939e273f84cd47a138b9db4c8c61a5372:docker-compose.yaml
